### ISSUE TITLE
Hope to add publication month information 

### ISSUE THREAD

**Issue by Yang-sheep-hub** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#1]
Thanks for authors careful collection. It helps a lot. As we all known,research papers on diffusion are rapidly increasing in number. I hope to add paper publication month information to know the timeline and relationship about important work.

**Comment by caopulan** [comment]
Sounds good. We will add the date in the follow-up. We are currently organizing in the order of the arXiv date. You can refer to that for now.

**Comment by caopulan** [comment]
> Thanks for authors careful collection. It helps a lot. As we all known,research papers on diffusion are rapidly increasing in number. I hope to add paper publication month information to know the timeline and relationship about important work.

We have added month!

**Comment by Yang-sheep-hub** [comment]
Thank you for your effort!
