### ISSUE TITLE
Paper update

### ISSUE THREAD

**Issue by zwcolin** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#10]
It would be great to add our TokenCompose paper to the category of "Advanced Text-Conditioned Generation."

Paper name: TokenCompose: Grounding Diffusion with Token-level Supervision
Paper link: https://arxiv.org/abs/2312.03626
Conference: CVPR 2024

Related area: Advanced Text-Conditioned Generation

Thank you!

**Comment by caopulan** [comment]
Done!
