### ISSUE TITLE
Paper update

### ISSUE THREAD

**Issue by huanngzh** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#11]
We would be grateful if if you can add our paper _Parts2Whole_.
title: From Parts to Whole: A Unified Reference Framework for Controllable Human Image Generation
arxiv: https://arxiv.org/abs/2404.15267
code: https://github.com/huanngzh/Parts2Whole
project page: https://huanngzh.github.io/Parts2Whole/

**Comment by caopulan** [comment]
Done. Please consider citing our survey paper if you find it useful :)
