### ISSUE TITLE
Paper Update

### ISSUE THREAD

**Issue by FaceAdapter** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#13]
I would be extremely grateful if you could kindly consider including our latest paper, code, and Gradio in the project. We recently made them open source just a few days ago and would be honored to have them included:

Person-Driven Generation
---
[Arxiv] Face Adapter for Pre-Trained Diffusion Models with Fine-Grained ID and Attribute Control
https://github.com/FaceAdapter/Face-Adapter
https://arxiv.org/pdf/2405.12970

**Comment by caopulan** [comment]
Done
