### ISSUE TITLE
add papers of text rendering

### ISSUE THREAD

**Issue by wanghaoyu33437** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#16]
1. Glyph-ByT5: A Customized Text Encoder for Accurate Visual Text Rendering
2. 2403.09622
3. ECCV 2024

1. GlyphDraw2: Automatic Generation of Complex Glyph Posters with Diffusion Models and Large Language Models
2. 2407.02252
3. arXiv 2024

**Comment by caopulan** [comment]
Done.
