### ISSUE TITLE
Paper Update

### ISSUE THREAD

**Issue by Correr-Zhou** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#19]
Hi, there. 👋
I will be greatly grateful if you can include our recent paper in the section of Subject-Driven Generation:
1. Paper title: MagicTailor: Component-Controllable Personalization in Text-to-Image Diffusion Models
2. arXiv ID: 2410.13370
3. Publication status: Preprint

Thanks for your time and attention.

**Comment by caopulan** [comment]
Done.
