### ISSUE TITLE
How about Papers with Code ?

### ISSUE THREAD

**Issue by debasmitdas** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#4]
How about we can add these papers to https://paperswithcode.com/task/diffusion-personalization. I have already added a few.

**Comment by caopulan** [comment]
I have already added our paper in papers with code (we now focus on controllable generation instead of only personalization). https://paperswithcode.com/paper/controllable-generation-with-text-to-image. Thanks for your comment.
