### ISSUE TITLE
Add ICCV2023 paper "BoxDiff" to the category of Spatial Control

### ISSUE THREAD

**Issue by Sierkinhane** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#7]
It would be great to add our boxdiff to the category of "Spatial Control".

Paper name: BoxDiff: Text-to-Image Synthesis with Training-Free Box-Constrained Diffusion
Paper link: https://arxiv.org/abs/2307.10816
Code link: https://github.com/showlab/BoxDiff

Related area: Spatial Control

Thank you!

**Comment by caopulan** [comment]
Thanks for your comment. I have added BoxDiff in Spatial Control.

**Comment by Sierkinhane** [comment]
It would be nice to add our paper to the "spatial control" section in the survey paper :)

**Comment by caopulan** [comment]
> It would be nice to add our paper to the "spatial control" section in the survey paper :)

Sorry we didn't notice this paper, we will include it in the next version.

**Comment by Sierkinhane** [comment]
Thanks.
