### ISSUE TITLE
Paper update

### ISSUE THREAD

**Issue by Tianhao-Qi** [PRIV-Creation/Awesome-Controllable-T2I-Diffusion-Models#9]
It would be great if you can add our paper DEADiff accepted by CVPR 2024 to Style-Driven Generation.
title: DEADiff: An Efficient Stylization Diffusion Model with Disentangled Representations
arxiv: https://arxiv.org/abs/2403.06951
code: https://github.com/Tianhao-Qi/DEADiff_code
project page: https://tianhao-qi.github.io/DEADiff/

**Comment by caopulan** [comment]
done
